import {Injectable} from "@angular/core";
import { PhotographerDetail } from "../models/photographer-detail";
import {PricingItem} from "../models/pricing-item";

@Injectable({
  providedIn: 'root'
})

export class PhotoGrapherService {
  private readonly photographerDetails: PhotographerDetail[]=[
    { id: 1, nom: 'Marlène Atangana',   specialite: 'Mariage & Événementiel',certifie: true, bio:'Photographe professionnelle spécialisée dans les mariages et les portraits depuis plus de 10 ans.',categories:['Mariage','Cérémonie','Couple'],portfolio:[ {id: 1,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 2,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 3,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'}],review:[{id: 1, auteur: 'Estelle N',note:5,texte:'Marlène a sublimé notre mariage. Photos livrées dans les délais, qualité exceptionnelle',date:'il y a 2 sem.' },{id: 2, auteur: 'Boris K.',note:5,texte:'Très professionnelle, à l\'écoute. Je recommande vivement.',date:'il y a 1 mois' },{id: 3, auteur: 'Christelle A.',note:4,texte:'Belles photos, ambiance détendue le jour J.',date:'il y a 2 mois' }], tarrif:[{libelle:'Séance 1 heure',prix:45000},{libelle:'Demi-journée',prix: 85000},{libelle:'Journée complète',prix:150000}]},
    { id: 2, nom: 'Hervé Nkoulou',    specialite: 'Portrait & Corporate',  certifie: true ,bio:'Spécialiste du portrait corporate et des shootings d\'entreprise. Studio mobile disponible.',categories:['Portrait','Corporate','Studio'],portfolio:[ {id: 1,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 2,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 3,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'}],review:[{id: 1, auteur: 'Estelle N',note:5,texte:'Marlène a sublimé notre mariage. Photos livrées dans les délais, qualité exceptionnelle',date:'il y a 2 sem.' },{id: 2, auteur: 'Boris K.',note:5,texte:'Très professionnelle, à l\'écoute. Je recommande vivement.',date:'il y a 1 mois' },{id: 3, auteur: 'Christelle A.',note:4,texte:'Belles photos, ambiance détendue le jour J.',date:'il y a 2 mois' }], tarrif:[{libelle:'Séance 1 heure',prix:45000}]},
    { id: 3, nom: 'Sandrine Bilong',  specialite: 'Mode & Studio',   certifie: true, bio:'Direction artistique mode et éditorial. Collaborations avec créateurs locaux.',categories:['Mode','Éditorial','Beauté'],portfolio:[ {id: 1,url: 'https://www.bing.com/th/id/OIP.SrGTet6ABRt7aBBUdC5UmAHaE7?w=193&h=135&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 2,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 3,url: 'https://www.bing.com/th/id/OIP.Lwbkc2wT3GyLpVI9yt6EvwHaFj?w=193&h=145&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'}] ,review:[{id: 1, auteur: 'Estelle N',note:5,texte:'Marlène a sublimé notre mariage. Photos livrées dans les délais, qualité exceptionnelle',date:'il y a 2 sem.' },{id: 2, auteur: 'Boris K.',note:5,texte:'Très professionnelle, à l\'écoute. Je recommande vivement.',date:'il y a 1 mois' },{id: 3, auteur: 'Christelle A.',note:4,texte:'Belles photos, ambiance détendue le jour J.',date:'il y a 2 mois' }], tarrif:[{libelle:'Séance 1 heure',prix:45000}]},
    { id: 4, nom: 'Aïcha Fouda',      specialite: 'Grossesse & Naissance',   certifie: true ,bio:'Photographe maternité et nouveau-né, séances douces en studio cocooning.',categories:['Grossesse','Naissance','Famille'],portfolio:[ {id: 1,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 2,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 3,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'}],review:[{id: 1, auteur: 'Estelle N',note:5,texte:'Marlène a sublimé notre mariage. Photos livrées dans les délais, qualité exceptionnelle',date:'il y a 2 sem.' },{id: 2, auteur: 'Boris K.',note:5,texte:'Très professionnelle, à l\'écoute. Je recommande vivement.',date:'il y a 1 mois' },{id: 3, auteur: 'Christelle A.',note:4,texte:'Belles photos, ambiance détendue le jour J.',date:'il y a 2 mois' }], tarrif:[{libelle:'Séance 1 heure',prix:45000}]},
    { id: 5, nom: 'Patrick Mbarga',   specialite: 'Événementiel',    certifie: false,bio:'Couverture d\'événements culturels et concerts. Livraison rapide.',categories:['Concert','Festival','Soirée'],portfolio:[ {id: 1,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 2,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 3,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'}] ,review:[{id: 1, auteur: 'Estelle N',note:5,texte:'Marlène a sublimé notre mariage. Photos livrées dans les délais, qualité exceptionnelle',date:'il y a 2 sem.' },{id: 2, auteur: 'Boris K.',note:5,texte:'Très professionnelle, à l\'écoute. Je recommande vivement.',date:'il y a 1 mois' },{id: 3, auteur: 'Christelle A.',note:4,texte:'Belles photos, ambiance détendue le jour J.',date:'il y a 2 mois' }], tarrif:[{libelle:'Séance 1 heure',prix:45000}]},
    { id: 6, nom: 'Joël Tchamba',    specialite: 'Immobilier & Produit',  certifie: true ,bio:'Photographie immobilière et packshot produit pour e-commerce.', categories:['Immobilier','Produit','Drone'],portfolio:[ {id: 1,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 2,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'},{id: 3,url: 'https://www.bing.com/th/id/OIP.6HCAqp2IPX_KcmEE1a7xeQHaKX?w=193&h=270&c=8&rs=1&qlt=90&r=0&o=6&dpr=1.3&pid=ImgAns&rm=2', label: 'Mariage'}],review:[{id: 1, auteur: 'Estelle N',note:5,texte:'Marlène a sublimé notre mariage. Photos livrées dans les délais, qualité exceptionnelle',date:'il y a 2 sem.' },{id: 2, auteur: 'Boris K.',note:5,texte:'Très professionnelle, à l\'écoute. Je recommande vivement.',date:'il y a 1 mois' },{id: 3, auteur: 'Christelle A.',note:4,texte:'Belles photos, ambiance détendue le jour J.',date:'il y a 2 mois' }], tarrif:[{libelle:'Séance 1 heure',prix:45000}]}
  ];

  async getById(id: number): Promise<PhotographerDetail | undefined> {
    return this.photographerDetails.find(
      p => p.id === id
    );
  }
}
